function About() {
    return <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras egestas neque mi, a placerat augue tincidunt sit amet. Aenean porta malesuada justo, quis posuere ligula luctus nec. Integer aliquet mi convallis, consequat enim ut, finibus diam. Cras neque mauris, tempus vel consequat at, ultricies ut diam. Fusce at convallis justo. Suspendisse placerat interdum finibus. Sed viverra aliquet euismod. Aliquam vehicula, nibh ac pharetra vehicula, metus metus bibendum ipsum, non blandit eros purus sed ipsum. Curabitur id convallis risus. Cras sollicitudin risus ultricies ante venenatis, non imperdiet arcu suscipit. Nam quis leo et elit facilisis semper.

        Nam sit amet elit vel nunc molestie accumsan a at leo. Maecenas et egestas libero. Cras a tempor diam. Praesent rhoncus rhoncus porttitor. Nulla quis massa nisi. Aliquam id suscipit nisi. Nullam tellus nulla, tristique tempor quam consequat, ornare condimentum dui. Integer id erat et ipsum scelerisque pellentesque. Morbi fermentum iaculis leo in dictum. Suspendisse potenti. Maecenas nibh lorem, rutrum ac velit quis, eleifend sodales quam. Sed imperdiet sem eu arcu tempus, sed tristique nunc rhoncus.

        Donec et leo vulputate, finibus nunc id, tincidunt eros. Nullam finibus turpis id lobortis faucibus. Suspendisse congue vestibulum ante sit amet molestie. Etiam sit amet mi at mi efficitur suscipit. Aenean eleifend at odio in dignissim. Pellentesque egestas purus eget eros iaculis finibus. Sed sit amet feugiat urna, vitae sagittis justo. Etiam quis est sit amet augue vulputate tempus in pulvinar massa. Mauris vehicula nibh nisl, et ornare arcu dictum quis.

        Morbi pellentesque neque nisi, pulvinar hendrerit orci elementum sit amet. Praesent a varius sem. Nunc at neque vel quam maximus porta vitae non sem. Cras pharetra suscipit semper. Ut eu tempor diam. Suspendisse sit amet nibh sit amet turpis viverra molestie. Aliquam ut gravida est. Nunc efficitur suscipit tortor, bibendum volutpat enim congue vel. Etiam euismod odio lacinia massa mattis molestie.

        Quisque eu lorem sit amet eros faucibus luctus. Donec vel ultricies lectus, vitae tempus nisi. Quisque eget rutrum sem. Nullam in nisl enim. Proin eros dolor, volutpat at ex euismod, venenatis eleifend massa. Vestibulum convallis venenatis mi. Pellentesque massa diam, scelerisque et dapibus et, tincidunt egestas nisi. Praesent non velit magna. Pellentesque quis sodales quam. Vestibulum luctus risus non ante eleifend, eu malesuada dui tincidunt. Maecenas a tortor luctus, dapibus arcu sit amet, euismod velit. Proin id venenatis mauris. Nam sit amet magna sed erat posuere laoreet ut ut tellus. Quisque id lectus et eros rhoncus sollicitudin. Integer sed commodo diam.
    </p>
}

export default About;